### ISSUE TITLE
CLI Tool should run on PHP 8.1

### ISSUE THREAD

**Issue by Jamesclark32** [spinupwp/spinupwp-cli#44]
## Current Outcome
Currently the CLI tool isn't functional on PHP 8.1, and encounters `deprecated` errors on a number of dependancies. 

## Desired Outcome
Ideally the CLI tool would work on PHP 8.1.

## Acceptance Criteria

- [ ] All functionality should work on PHP 8.1 as it does on other versions of PHP. 
- [ ] Dependancies should be updates as appropriate

**Comment by rtvenge** [comment]
Did this ever get released? It is a little bit of a pain because every time I run `brew` (because, homebrew 😆) it updates my local php and it has to be linked back to 8.0.

**Comment by Jamesclark32** [comment]
@rtvenge Thanks for your patience! This has now been released.
